iosite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^spierdon/', include('spierdon.urls', namespace='spierdon'), name='main'),
    url(r'^$', RedirectView.as_view(url='/spierdon/')),
    url(r'^accounts/', include('registration.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spierdon/urls.py
from django.conf.urls import url
from . import views

"""
URL patterns used by 'spierdon' app.
"""
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ranking/', views.ranking, name='ranking'),
    url(r'^challenge/(?P<challenge_id>[0-9]+)/complete$', views.complete_challenge, name='complete_challenge'),
    url(r'^challenge/(?P<challenge_id>[0-9]+)/join/', views.join_challenge, name='join_challenge'),
    url(r'^challenge/new/', views.add_challenge, name='add_challange'),
    url(r'^challenge/(?P<challenge_id>[0-9]+)/block/', views.block_challenge, name='block_challange'),
    url(r'^challenges/completed/', views.get_completed, name='get_completed'),
    url(r'^challenges/available/', views.get_challenges, name='get_challenges'),
]

spierdon/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from math import log, floor, ceil
from django.db.models.signals import post_save
from django.forms import ModelForm


class SpierdonUser(models.Model):
    user = models.OneToOneField(User)
    exp = models.IntegerField(null=False, default=0)
    public_level = models.BooleanField(default=False)

    """
    Calculates spierdon's level based on experience value.
    """

    def compute_level(self):
        points = 0
        for level in range(1, 100):
            diff = int(level + 100 * pow(2, float(level) / 7))
            previous_points = points / 4
            points += diff
            # print("Level %d = %d" % (level + 1, points / 4))
            if points / 4 > self.exp:
                return {
                    "current": level,
                    "previous": previous_points,
                    "next": ceil(points / 4),
                }

    @property
    def level(self):
        return self.compute_level()["current"]

    @property
    def remaining(self):
        level_info = self.compute_level()
        return level_info["next"] - self.exp

    @property
    def percent(self):
        level_info = self.compute_level()
        return ceil((self.exp - level_info["previous"]) / (level_info["next"] - level_info["previous"])*100)

    def __str__(self):
        """
        Return string representation of SpierdonUser object.
        """
        return self.user.__str__() + ' ' + self.level.__str__() + ' lvl'


def create_user_profile(sender, instance, created, **kwargs):
    """
    Create SpierdonUser object associated with newly created User.
    """
    if created:
        _, _ = SpierdonUser.objects.get_or_create(user=instance)


post_save.connect(create_user_profile, sender=User)


class Challenge(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    exp = models.IntegerField(null=False, default=10)
    min_level = models.IntegerField(null=False, default=0)
    max_level = models.IntegerField(null=False, default=9999)
    picture = models.ImageField(upload_to='upload/', default='default.jpg')
    blocked=models.BooleanField(default=False, null=False)

    def __str__(self):
        """
        Return the string representation of Challenge object.
        :return:
        """
        return "%s (exp: %d)" % (self.name, self.exp)


class UserActiveChallenge(models.Model):
    challenge = models.ForeignKey(Challenge, null=False)
    user = models.ForeignKey(SpierdonUser, null=False)
    completed = models.BooleanField(default=False)
    blocked = models.BooleanField(default=False, null=False)

    def __str__(self):
        """
        Return the string representation of UserActiveChallenge object.
        """
        return "%s %s (completed: %s)" % (self.user, self.challenge, self.completed)


class ChallengeForm(ModelForm):
    class Meta:
        model = Challenge
        fields = ['name', 'description', 'exp', 'min_level', 'max_level', 'picture']

spierdon/views.py
from django.shortcuts import render_to_response, get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import SpierdonUser, Challenge, UserActiveChallenge, ChallengeForm
from django.core.urlresolvers import reverse
from django.template import RequestContext
import random


@login_required
def index(request):
    """
    Generate main page.

    :param request: HttpRequest object
    :return: HttpResponse object with user and challenges info included
    """
    user_challenges = Challenge.objects.filter(
        useractivechallenge__user__user__username=request.user.username,
        useractivechallenge__completed=False,
        useractivechallenge__blocked=False)

    spierdon_user = SpierdonUser.objects.get(user=request.user)

    return render(request, "index.html", {
        'user': request.user,
        'spierdon': spierdon_user,
        'user_challenges': user_challenges,
        'ranking': SpierdonUser.objects.order_by("-exp")[:4],
        'has_public': request.user.spierdonuser.public_level,
    })


@login_required
def get_completed(request):
    items = Challenge.objects.filter(
        useractivechallenge__user__user__username=request.user.username,
        useractivechallenge__completed=True, useractivechallenge__blocked=False)

    return render(request, "completed.html", {
        'items': items,
    }, RequestContext(request))


@login_required
def complete_challenge(request, challenge_id):
    """
    Mark challenge as completed and redirect to main page.

    :param request: HttpRequest object
    :param challenge_id: challenge's id
    :return: HttpResponseRedirect object
    """

    challenge_to_complete = get_object_or_404(UserActiveChallenge, challenge__pk=challenge_id)

    challenge_to_complete.completed = True
    challenge_to_complete.save()

    challenge_to_complete.user.exp += challenge_to_complete.challenge.exp;
    challenge_to_complete.user.save();

    return HttpResponseRedirect(reverse('spierdon:index'))


@login_required
def ranking(request):
    """
    Create ranking of users. Work only if logged user shares its statistics to the public.

    :param request: HttpRequest object
    :return: HttpResponse object with ranking dict
    """
    if request.method == 'POST':
        request.user.spierdonuser.public_level = not request.user.spierdonuser.public_level
        request.user.spierdonuser.save()

    return render(request, "ranking.html", {
        "items": SpierdonUser.objects.order_by("-exp"),
        "has_public": request.user.spierdonuser.public_level,
    })


@login_required
def add_challenge(request):
    """
    Create add challenge form.

    :param request: HttpRequest object
    :return: HttpResponseRedirect object
    """
    if request.method == 'POST':
        form = ChallengeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                # challenge = form.save(commit=False)
                # challenge.picture = form.cleaned_data['picture']
                # challenge.save()
                return HttpResponseRedirect('/')
            except:
                pass
    return render(request, 'addChallange.html', {'form': ChallengeForm()},
                  context_instance=RequestContext(request))


@login_required
def block_challenge(request, challenge_id):
    """
    Votes for block challenge form.

    :param request: HttpRequest object
    :return: HttpResponseRedirect object
    """
    challenge_to_block = get_object_or_404(UserActiveChallenge, challenge__pk=challenge_id)

    challenge_to_block.blocked = True
    challenge_to_block.save()

    if (UserActiveChallenge.objects.filter(pk=challenge_id, blocked=True).count() > 1):
        challenge_to_block.challenge.blocked = True
        challenge_to_block.challenge.save()

    return HttpResponseRedirect(reverse('spierdon:index'))


@login_required
def get_challenges(request):
    """
    Get five random challenges available for current user (ie. those which are assigned to current user's level
    and not already completed).

    :param request: HttpRequest object
    :return: HttpResponse object with drawn challenges
    """
    challenges = Challenge.objects.filter(min_level__lte=request.user.spierdonuser.level,
                                          max_level__gte=request.user.spierdonuser.level,
                                          blocked=False)
    user_challenges = [i.challenge for i in UserActiveChallenge.objects.filter(user__exact=request.user.spierdonuser)]
    challenges = [e for e in challenges if e not in user_challenges]
    random.shuffle(challenges)
    return render(request, 'newChallenge.html', {
        "items": challenges[:5]
    })


@login_required
def join_challenge(request, challenge_id):
    """
    Join user to challenge with given id.

    :param request: HttpRequest object
    :param challenge_id: id of challenge to which user wants to join
    :return: HttpResponse of index() method
    """
    _, created = UserActiveChallenge.objects.get_or_create(challenge=Challenge.objects.get(pk=challenge_id),
                                                           user=SpierdonUser.objects.get(user=request.user))
    return HttpResponseRedirect(reverse('spierdon:index')) if created else HttpResponse(
        "You already joined to this challenge.")

spierdon/templates/addChallange.html
{% extends "form.html" %}
{% block title %}Add challenge{% endblock %}

{% block content %}

<h2 class="form-signin-heading">Add challenge</h2>
{{ form.media }}
<form class="form-signin" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% load bootstrap %}
    {{ form|bootstrap }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
</form>

{% endblock %}

spierdon/templates/completed.html
{% extends "full.html" %}
{% block title %}Completed{% endblock %}

{% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<div container-fluid>
    <table class="table-hover">
        <thead class="text-center">
            <th style="padding: 10px; text-align: center">Name</th>
            <th style="padding: 10px; text-align: center">Description</th>
            <th style="padding: 10px; text-align: center">Exp</th>
            <th style="padding: 10px; text-align: center">Picture</th>
            <th style="padding: 10px; text-align: center">Share</th>
        </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td style="padding: 10px; text-align: center">{{ item.name }}</td>
            <td style="padding: 10px">{{ item.description }}</td>
            <td style="padding: 10px; text-align: center">{{ item.exp }}</td>
            <td style="padding: 10px"><img class="challenge-image" src="{{ item.picture.url }}"></td>
            <td>
                <div class="fb-share-button center-block" style="width: 65px;" data-href="{{ urlencode }}" data-layout="button" data-size="small"
                     data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank"
                                                  href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri|urlencode }}&amp;src=sdkpreparse">Udostępnij</a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

spierdon/templates/index.html
{% extends "full.html" %}
{% block title %}Welcome{% endblock %}

{% block content %}



<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="well well-lg" style="background-color: white;">
            <div class="row">

                <div class="col-sm-6 col-md-8">
                    <h4>Hi, {{ user }}!</h4>
                    <p>
                        Level: {{spierdon.level|floatformat:"0"}}
                        <br/>
                        Exp: {{ spierdon.exp }}
                        <br/>
                        {{ spierdon.remaining }} experience points to next level
                    </p>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{ spierdon.percent }}" aria-valuemin="0"
                             aria-valuemax="100" style="width: {{ spierdon.percent }}%;">
                            <span class="sr-only">{{ spierdon.percent }}% Complete</span>
                        </div>
                    </div>
                    <a role="button" class="btn btn-primary" href="{% url 'spierdon:get_challenges' %}">
                        Available challenges
                    </a>
                    <a role="button" class="btn btn-default" href="{% url 'spierdon:add_challange' %}">Add new</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="well well-lg" style="background-color: white;">
            <h4>Top 5</h4>
            <table class="table table-condensed">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Level</th>
                </tr>
                {% for item in ranking %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    {% if has_public %}
                    <td>{{ item.user.username }}</td>
                    {% else %}
                    <td>-</td>
                    {% endif %}
                    <td>{{ item.level }}</td>
                </tr>
                {% endfor %}
            </table>
            {% if ranking.count >= 4 %}
            <a href="ranking">More</a>
            {% endif %}
        </div>
    </div>
</div>

<h3>Joined challenges</h3>

    {% if user_challenges.count > 0 %}
        <div class="row">
            {% for user_challenge in user_challenges %}
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="{{ user_challenge.picture.url }}">
                        <div class="caption">
                            <h3>{{ user_challenge.name }}</h3>
                            <p>Exp: {{ user_challenge.exp }}</p>
                            <p>{{ user_challenge.description }}</p>
                            <div class="input-group">

                                <div class="input-group-btn">

                                    <form action="{% url 'spierdon:complete_challenge' user_challenge.id %}" method="post">
                                        {% csrf_token %}
                                        <button class="btn btn-default" role="button" type="submit">Complete</button>
                                    </form>
                                </div>
                                <div class="input-group-btn">
                                <form action="{% url 'spierdon:block_challange' user_challenge.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" role="button" type="submit">Block</button>
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div>
            <a role="button" class="btn btn-warning" href="{% url 'spierdon:get_challenges' %}">Join now</a>
        </div>
    {% endif %}

{% endblock %}

spierdon/templates/newChallenge.html
{% extends "full.html" %}
{% block title %}New Challenge{% endblock %}

{% block content %}

<div container-fluid>
    <table class="table-hover ">
            <thead>
                <th style="padding: 10px">Name</th>
                <th style="padding: 10px">Description</th>
                <th style="padding: 10px">Exp</th>
                <th style="padding: 10px">Picture</th>
                <th style="padding: 10px"></th>
            </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td style="padding: 10px">{{ item.name }}</td>
                <td style="padding: 10px">{{ item.description }}</td>
                <td style="padding: 10px">{{ item.exp }}</td>
                <td style="padding: 10px"><img class="challenge-image" src="{{ item.picture.url }}" style="width: 100px;"></td>
                <td><a href="{% url 'spierdon:join_challenge' item.id %}">Join</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

spierdon/templates/rank.html
{% extends "base.html" %}
{% block title %}Rank{% endblock %}
{% block content %}
{% if has_public %}
<table>
    <tr>
        <th>Nr</th>
        <th>Name</th>
        <th>Level</th>
    </tr>
    {% for item in items %}
    <tr>
        <th>{{ forloop.counter }}</th>
        <th>{{ item.user.username }}</th>
        <th>{{ item.level }}</th>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Rank is available for users who published their level.</p>
{% endif %}
{% endblock %}

spierdon/templates/ranking.html
{% extends "full.html" %}
{% block title %}Ranking{% endblock %}
{% block content %}
{% if has_public %}

<h2>Ranking</h2>
<table class="table table-condensed">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Level</th>
    </tr>
    {% for item in items %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ item.user.username }}</td>
        <td>{{ item.level }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h2 class="text-info">Unavailable</h2>
<form method="post">
    {% csrf_token %}
    <p class="help-block">
        Unfortunately, current ranking is available only for users who published their level.
    </p>
    <button class="btn btn-primary" type="submit">Publish</button>
</form>

{% endif %}
{% endblock %}

spierdon/templates/userPanel.html
<div class="userPanel">
    <div class="userInformation">
        <h1>{{user.username}}<br/>
        {{spierdon.level|floatformat:"0"}} level</h1>
    </div>
    <div class="operations">
        <a href="{% url 'auth_logout' %}">logout</a>
        <a href="{% url 'auth_password_change' %}">password change</a>
        {% if spierdon.level > 20 %}
        <a href="{% url 'spierdon:add_challange' %}">add challange</a>
        {% endif %}
    </div>

</div>