iosite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^spierdon/', include('spierdon.urls', namespace='spierdon'), name='main'),
    url(r'^$', RedirectView.as_view(url='/spierdon/')),
    url(r'^accounts/', include('registration.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spierdon/urls.py
from django.conf.urls import url
from . import views

"""
URL patterns used by 'spierdon' app.
"""
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ranking/', views.ranking, name='ranking'),
    url(r'^challenge/(?P<challenge_id>[0-9]+)/complete$', views.complete_challenge, name='complete_challenge'),
    url(r'^challenge/(?P<challenge_id>[0-9]+)/join/', views.join_challenge, name='join_challenge'),
    url(r'^challenge/new/', views.add_challenge, name='add_challange'),
    url(r'^challenge/(?P<challenge_id>[0-9]+)/block/', views.block_challenge, name='block_challange'),
    url(r'^challenges/completed/', views.get_completed, name='get_completed'),
    url(r'^challenges/available/', views.get_challenges, name='get_challenges'),
]

templates/base.html
{% load bootstrap3 %}
{% bootstrap_messages %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    <link rel="stylesheet" type="text/css" href="{% static 'spierdon/style.css' %}" />
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        {% block navbar %}
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'spierdon:index' %}">SPIERDON</a>
        </div>
        {% endblock %}
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/error.html
{% extends "form.html" %}

{% block title %}Error{% endblock %}

{% load widget_tweaks %}

{% block form %}
<h2 class="form-signin-heading">Error :(</h2>
<p class="help-block">
    {{ description }}
</p>
<a class="btn btn-lg btn-primary btn-block" href="javascript:history.go(1)" role="button">Go back</a>

{% endblock %}

templates/form.html
{% extends "base.html" %}

{% block title %}Log in{% endblock %}

{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        {% block form %}{% endblock %}
    </div>
</div>
{% endblock %}

templates/full.html
{% extends 'base.html' %}

{% block navbar %}

<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand">SPIERDON</a>
    {% if user.is_authenticated %}
    <p class="navbar-text"></p>
    {% endif %}
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
            <li
            {% if request.resolver_match.url_name == 'index' %} class="active"{% endif %}>
                <a href="{% url 'spierdon:index' %}">Overview</a>
            </li>
            <li
            {% if request.resolver_match.url_name == 'get_challenges' %} class="active"{% endif %}>
                <a href="{% url 'spierdon:get_challenges' %}">Challenges</a>
            </li>
            <li
            {% if request.resolver_match.url_name == 'get_completed' %} class="active"{% endif %}>
                <a href="{% url 'spierdon:get_completed' %}">Completed</a>
            </li>
            <li
            {% if request.resolver_match.url_name == 'ranking' %} class="active"{% endif %}>
                <a href="{% url 'spierdon:ranking' %}">Ranking</a>
            </li>
        {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false">Hi, {{ user.get_username }} <span class="caret"></span></a>
            <ul class="dropdown-menu">
                {% if user_challenges.count < 4 %}
                <li>
                    <a href="{% url 'spierdon:add_challange' %}">Add challange</a>
                </li>
                {% endif %}
                <li><a href="{% url 'auth_password_change' %}">Change password</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            </ul>
    </ul>
    {% comment %}
    <form class="navbar-form navbar-right" role="search" action="" method="get">
        <div class="form-group">
            <input type="text" name="query" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    {% endcomment %}
</div><!-- /.navbar-collapse -->
{% endblock %}

{% block content %}
{% endblock %}